/**
 * Created by CSpan on 30-Jun-17.
 */
var Config = (function () {
    function Config() {
        this.formPage = '<!-- Page Heading --> <div class="row"> <div class="col-lg-12"> <!-- <h1 class="page-header"> Form </h1> --> <ol class="breadcrumb"> <li> <i class="fa fa-dashboard"></i> <a href="index.html">Dashboard</a> </li> <li class="active"> <i class="fa fa-edit"></i> Form </li> </ol> </div> </div> <!-- /.row --> <div class="row"> <div class="col-lg-12"> <form role="form" id="formING" name="formING"> <div class="form-group"> <label>Klantnaam</label> <input id="customer" class="form-control"> </div> <div class="form-group"> <label>KVK nummer</label> <input id="kvk" class="form-control"> </div> <div class="form-group"> <label>Adres</label> <input id="address" class="form-control"> </div> <div class="form-group"> <label>Postcode</label> <input id="postcode" class="form-control"> </div> <div class="form-group"> <label>Gemeente</label> <input id="gemeente" class="form-control"> </div> <div class="form-group"> <label>Hoogte lening</label> <input id="loan" class="form-control"> </div> <div class="form-group"> <label>Type lening</label> <select id="type" class="form-control"> <option value="restaurant">Restaurant</option> <option value="kantoor">Kantoor</option> </select> </div> <button type="submit" class="btn btn-default">Submit Button</button> <button type="reset" class="btn btn-default">Reset Button</button> </form> </div> </div> <!-- /.row -->';
        this.mapPage = '<!-- <h1 class="page-header"> Map </h1> --> <ol class="breadcrumb"> <li> <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a> </li> <li class="active"> <i class="fa fa-edit"></i> Map </li> </ol> <!-- Page Heading --> <div class="row"> <div class="col-lg-12"> <nav id="menu"></nav> <div id="map"></div> </div> </div> <!-- /.row --><div class="row"><div class="col-lg-4"><div class="panel panel-green"><div class="panel-heading"><h3 class="panel-title" id="leeftijdTitle"><i class="fa fa-long-arrow-right"></i>Leeftijdsverdeling per buurt (%)</h3></div><div class="panel-body"><div class="flot-chart"><div class="flot-chart-content" id="flot-pie-chart"><center>Klik op een buurt</center></div></div></div></div></div><div class="col-lg-4"><div class="panel panel-yellow"><div class="panel-heading"><h3 class="panel-title" id="bagTitle"><i class="fa fa-long-arrow-right"></i> BAG pand informatie</h3></div><div class="panel-body"><div class="flot-chart"><div class="flot-chart-content" id="bagTable"><center>Klik op een BAG pand</center></div></div></div></div></div><div class="col-lg-4"><div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title" id="fmeTitle"><i class="fa fa-long-arrow-right"></i> FME Cloud data</h3></div><div class="panel-body"><div class="flot-chart"><div class="flot-chart-content" id="fmeContent">Data van Martins FME Cloud komt vrijdag</div></div></div></div></div></div>';
        this.mapBoxAccessToken = 'pk.eyJ1IjoiaXZvMTEyMzUiLCJhIjoieV82bFVfNCJ9.G8mrfJOA07edDDj6Bep2bQ';
        this.mapBoxStyle = 'mapbox://styles/ivo11235/cj40zzvy43klk2rozfylmtc5y';
        this.geoCodeUrl = 'https://nominatim.openstreetmap.org/search?polygon=1&addressdetails=1&format=json&limit=1&q=';
        this.bagUrl = 'https://geodata.nationaalgeoregister.nl/bag/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=bag:pand&SRSNAME=EPSG:4326&outputFormat=json';
        this.buurtUrl = 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2016/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=wijkenbuurten2016:cbs_buurten_2016&SRSNAME=EPSG:4326&outputFormat=json';
        this.fmeUrl = 'proxy/proxy.ashx?https://ingservice-martinkoch.fmecloud.com/fmedatastreaming/WFSservices/ING_wfsServer.fmw?request=GetFeature&TYPENAME=ING:kvkdata&outputFormat=json';
    }
    return Config;
}());
//# sourceMappingURL=config.js.map